# Configuração do Serviço Gestor
spring.application.name=AvaliacaoGestorSD
server.port=8080
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/avaliacaogestor
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true


# URLs dos serviços (PC2)
pessoas.url=http://26.93.35.164:8081
veiculos.url=http://26.93.35.164:8082